# Generated by Django 3.2.9 on 2021-11-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='duration',
        ),
        migrations.AddField(
            model_name='podcast',
            name='duration_in_sec',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
